processor:
  app:
    name: processor
  port: 8040
  log:
    level: DEBUG
  database:
    username: admin
    password: pr0t&ct&d
    ddlAuto: validate
    showSql: false

server:
  port: ${processor.port}
  servlet:
    context-path: /processor

spring:
  output:
    ansi:
      enabled: detect
  flyway:
    enabled: true
    schemas: processor
    locations: filesystem:src/main/resources/scripts/migration
    user: admin
    password: pr0t&ct&d
  application:
    name: ${processor.app.name}
  jackson:
    serialization:
      write-dates-as-timestamps: true
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:fadesp;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS processor
    username: ${processor.database.username}
    password: ${processor.database.password}
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      order_by:
        default_null_ordering: last
    hibernate:
      ddl-auto: ${processor.database.ddlAuto}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: ${processor.database.showSql}
    database-platform: org.hibernate.dialect.H2Dialect
    web:
      locale: pt_BR
      resources:
        add-mappings: false
    mvc:
      format:
        date: dd/MM/yyyy
      throw-exception-if-no-handler-found: true
    servlet:
      multipart:
        enabled: false

  logging:
    pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([${processor.app.name}]){magenta}%clr(%X{cdTransacao}){yellow}%clr(%X{contexto}){blue} %clr(%m%n){%5p} ${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
      file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([${colaborador.app.name}]){magenta}%clr(%X{contexto}){magenta}%clr(%X{cdTransacao}){magenta} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    level:
      com.fit: ${processor.log.level}
      root: INFO
